{
    "openapi": "3.0.0",
    "info": {
        "title": "API Sebo - PDW",
        "description": "API para Atividade PDW",
        "contact": {
            "nome": "Leonardo Galindo",
            "RA": "SP3081656"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:3000"
        }
    ],
    "paths": {
        "/users/signup": {
            "post": {
                "summary": "Cadastro de usuarios",
                "description": "Responsavel por cadastras novos usuarios",
                "tags": [
                    "Users"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/User"
                            },
                            "examples": {
                                "administrador": {
                                    "value": {
                                        "nome": "Leonardo Galindo",
                                        "email": "leonardogalindo8@outlook.com",
                                        "status": "ativo",
                                        "tipo": "administrador",
                                        "senha": "123",
                                        "area": "vendas",
                                        "data_inicio": "2023-10-02"
                                    }
                                },
                                "usuario_comum": {
                                    "value": {
                                        "nome": "Leonardo Galindo",
                                        "email": "leonardogalindo8@gmail.com",
                                        "status": "inativo",
                                        "tipo": "vendedor",
                                        "senha": "123"
                                    }
                                },
                                "area_data_comum": {
                                    "value": {
                                        "nome": "Leonardo Galindo",
                                        "email": "leonardogalindo8@gmail.com",
                                        "status": "inativo",
                                        "tipo": "vendedor",
                                        "senha": "123",
                                        "area": "vendas",
                                        "data_inicio": "2023-10-02"
                                    }
                                },
                                "area_data_adnin": {
                                    "value": {
                                        "nome": "Leonardo Galindo",
                                        "email": "leonardogalindo8@gmail.com",
                                        "status": "inativo",
                                        "tipo": "vendedor",
                                        "senha": "123"
                                    }
                                },
                                "campos_invalidos": {
                                    "value": {
                                        "nome": "Leonardo Galindo",
                                        "email": "leonardogalindo8@gmail.com",
                                        "status": "inativo",
                                        "tipo": "aaaaa",
                                        "senha": "123"
                                    }
                                },
                                "campos_nao_eviados": {
                                    "value": {
                                        "nome": "Leonardo Galindo",
                                        "email": "leonardogalindo8@gmail.com",
                                        "status": "inativo",
                                        "tipo": "vendedor",
                                        "senha": ""
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "401": {
                        "description": "Área e data de início não são válidas para tipos diferentes de administrador"
                    },
                    "400": {
                        "description": "Área e data de início são obrigatórias para administradores"
                    },
                    "200": {
                        "description": "Usuário criado com sucesso"
                    },
                    "201": {
                        "description": "Usuário admin criado com sucesso"
                    },
                    "411": {
                        "description": "Campos não enviados"
                    },
                    "406": {
                        "description": "Campos invalidos"
                    }
                }
            }
        },
        "/admin/users": {
            "get": {
                "description": "Visualizar usuarios",
                "summary": "Retorna usuarios cadastrados (sem contar os soft delete)",
                "tags": [
                    "Users"
                ],
                "responses": {
                    "200": {
                        "description": "Lista de usuarios"
                    }
                }
            }
        },
        "/users/{id}": {
            "put": {
                "description": "Alterar usuarios",
                "summary": "Alterar informações de usuarios atraves do id",
                "tags": [
                    "Users"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID do usuario",
                        "required": true
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/User"
                            },
                            "examples": {
                                "alteracao_comcluida": {
                                    "value": {
                                        "nome": "Thiago",
                                        "email": "thi@outlook.com",
                                        "status": "ativo",
                                        "tipo": "administrador",
                                        "senha": "123",
                                        "area": "MKT",
                                        "data_inicio": "2023-10-10"
                                    }
                                },
                                "data_area_admin": {
                                    "value": {
                                        "nome": "Thiago",
                                        "email": "thi@outlook.com",
                                        "status": "ativo",
                                        "tipo": "administrador",
                                        "senha": "123"
                                    }
                                },
                                "data_area_comum": {
                                    "value": {
                                        "nome": "Thiago",
                                        "email": "thi@outlook.com",
                                        "status": "ativo",
                                        "tipo": "vendedor",
                                        "senha": "123",
                                        "area": "MKT",
                                        "data_inicio": "2023-10-10"
                                    }
                                },
                                "tipo_invalido": {
                                    "value": {
                                        "nome": "Thiago",
                                        "email": "thi@outlook.com",
                                        "status": "ativo",
                                        "tipo": "aaaaa",
                                        "senha": "123"
                                    }
                                },
                                "campos_nao_eviados": {
                                    "value": {
                                        "nome": "Thiago",
                                        "email": "thi@outlook.com",
                                        "status": "ativo",
                                        "tipo": "vendedor",
                                        "senha": ""
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Usuario alterado com sucesso"
                    },
                    "401":{
                        "description": "Área e data de início não são válidas para tipos diferentes de administrador"
                    },
                    "400":{
                        "description":"Área e data de início são obrigatórias para administradores"
                    },
                    "406":{
                        "description": "Campos invalidos"
                    },
                    "411":{
                        "description": "Campos não enviados"
                    }
                }
            }, 
            "delete": {
                "description": "Soft delete para usuarios",
                "summary": "Soft delete para usuarios",
                "tags": [
                    "Users"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "ID do usuario",
                        "required": true
                    }
                ],
                "responses": {
                    "404": {
                        "description": "Usuario não encontrado ou já excluido"
                    },
                    "200": {
                        "description": "Usuario excluido com sucesso"
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "description": "Login de usuario",
                "summary": "Login de usuario",
                "tags": [
                    "Users"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/User"
                            },
                            "examples": {
                                "login_bem_sucedido": {
                                    "value": {
                                        "email": "leonardogalindo8@gmail.com",
                                        "senha": "123"
                                    }
                                },
                                "login_nao_realizado": {
                                    "value": {
                                        "email": "leonardogalindo8@gmail.com",
                                        "senha": "1234"
                                    }
                                },
                                "usario_nao_encontrado": {
                                    "value": {
                                        "email": "leonardo@gmail.com",
                                        "senha": "1234"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "login bem sucedido"
                    },
                    "401": {
                        "description": "credenciais invalidaas"
                    },
                    "404": {
                        "description": "Usuário não encontrado"
                    },
                    "411": {
                        "description": "Campos não enviados"
                    }
                }
            }
        },
        "/admin/login": {
            "post": {
                "description": "Login de admin",
                "summary": "Login de admin",
                "tags": [
                    "Users"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/User"
                            },
                            "examples": {
                                "login_bem_sucedido": {
                                    "value": {
                                        "email": "leonardogalindo8@outlook.com",
                                        "senha": "123"
                                    }
                                },
                                "login_nao_realizado": {
                                    "value": {
                                        "email": "leonardogalindo8@outlook.com",
                                        "senha": "1234"
                                    }
                                },
                                "usario_nao_encontrado": {
                                    "value": {
                                        "email": "leonardo@gmail.com",
                                        "senha": "1234"
                                    }
                                },
                                "campos_nao_eviados": {
                                    "value": {
                                        "email": "leonardo@gmail.com",
                                        "senha": ""
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "login bem sucedido"
                    },
                    "401": {
                        "description": "credenciais invalidaas"
                    },
                    "404": {
                        "description": "Usuário não encontrado"
                    },
                    "411": {
                        "description": "Campos não enviados"
                    }
                }
            }
        },
        "/admin/reports": {
            "get": {
                "description": "Visualizar quantidade de usuarios",
                "summary": "Retorna usuarios cadastrados no total",
                "tags": [
                    "Users"
                ],
                "responses": {
                    "200": {
                        "description": "Total de usuarios"
                    },
                    "500": {
                        "description": "erro ao contar usuarios"
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "User": {
                "type": "object",
                "properties": {
                    "nome": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "status": {
                        "type": "string",
                        "enum": [
                            "ativo",
                            "inativo"
                        ]
                    },
                    "tipo": {
                        "type": "string",
                        "enum": [
                            "vendedor",
                            "comprador",
                            "administrador"
                        ]
                    },
                    "senha": {
                        "type": "string"
                    },
                    "area": {
                        "type": "string"
                    },
                    "data_inicio": {
                        "type": "string",
                        "format": "date"
                    }
                }
            }
        }
    }
}